## Example

In [1]:
varA=list(range(10))
varB=list(range(10,20))
varC=list(range(20,30))

In [2]:
print (varA)
print (varB)
print (varC)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]


In [3]:
dataInALl=[varA,varB,varC]

In [4]:
dataInALl

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]

In [5]:
[sum(i) for i in dataInALl]

[45, 145, 245]

## Why we dont use the List for numerical data analysis?

Python is a slow language and struggles more on complex mathematical operations.

The values are object and are not the number type or any specific data types, they are pointer to the acutal number in the memory. 

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.


A numpy array is a single object for all the collection of the array with all numbers. they are much more efficeint on storing and also are faster during computations.

source: https://numpy.org/devdocs/user/quickstart.html

the core fundamental data type for numpy is an array.

In [6]:
!pip install numpy

In [7]:
import numpy as np

In [8]:
dataInALl

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]

In [9]:
sampeData=np.array(dataInALl)
sampeData

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [10]:
print ('size        ',sampeData.size)
print ('dimension   ',sampeData.ndim)
print ('shape       ',sampeData.shape)
print ('dtype       ',sampeData.dtype)
print ('flags       ',sampeData.flags)  #C contiguous the rows are stored as contiguous blocks of memory. #Fortran contiguous since the columns are in contiguous blocks of memory:
print ('strides     ',sampeData.strides) 

size         30
dimension    2
shape        (3, 10)
dtype        int64
flags          C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

strides      (80, 8)


In [11]:
sampeData2=np.array([[.4,.5,.6],[.4,.5,.6]])

In [12]:
print ('size        ',sampeData2.size)
print ('dimension   ',sampeData2.ndim)
print ('shape       ',sampeData2.shape)
print ('dtype       ',sampeData2.dtype)
print ('flags       ',sampeData2.flags)
print ('strides     ',sampeData2.strides)

size         6
dimension    2
shape        (2, 3)
dtype        float64
flags          C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

strides      (24, 8)


Ram does not have concept of row and column

strides:  24 bytes jump/skip to reach in row below and 8 bytes to jump in the side column

## Transpose

In [13]:
sampeData.T

array([[ 0, 10, 20],
       [ 1, 11, 21],
       [ 2, 12, 22],
       [ 3, 13, 23],
       [ 4, 14, 24],
       [ 5, 15, 25],
       [ 6, 16, 26],
       [ 7, 17, 27],
       [ 8, 18, 28],
       [ 9, 19, 29]])

In [14]:
sampeData.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [15]:
sampeData

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [16]:
sampeData.strides

(80, 8)

In [17]:
sampeData.transpose().strides

(8, 80)

Meaning the transpose is not a new copy they  are looking at the same place, and if you need a transpose just change your stride and no more copying the data or duplicating

##  Slicing in Numpy

In [18]:
sampeData

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [19]:
sampeData[:,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [20]:
sampeData[::]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [21]:
sampeData[:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [22]:
sampeData[1:,3:5]

array([[13, 14],
       [23, 24]])

In [23]:
sampeData[2][-1]

29

In [24]:
sampeData

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [25]:
sampeData.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [26]:
sampeData[::2].flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [27]:
sampeData.strides

(80, 8)

In [28]:
sampeData.dtype

dtype('int64')

In [29]:
sampeData = sampeData.astype("int32")

In [30]:
sampeData.strides

(40, 4)

In [31]:
sampeData.dtype

dtype('int32')

In [32]:
sampeData

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]], dtype=int32)

In [33]:
sampeData[::2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]], dtype=int32)

In [34]:
sampeData[::2].strides #because sampedata[1] is absent we must pass 80 bytes to access sampedate[:,0] 

(80, 4)

In [35]:
sampeData.strides

(40, 4)

doubled the byte skips as now jumping 2 rows and hence also confirming its not copying the data using the same memory as the original data

In [36]:
sampeData[::2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]], dtype=int32)

In [37]:
sampeData[:,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]], dtype=int32)

In [38]:
sampeData.strides

(40, 4)

In [39]:
sampeData[:3,:3].strides

(40, 4)

In [40]:
sampeData

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]], dtype=int32)

In [41]:
sampeData[::2,::2]

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28]], dtype=int32)

In [42]:
sampeData[::2,::2]

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28]], dtype=int32)

In [43]:
sampeData[::2,::2].strides

(80, 8)

In [44]:
sampeData[::2,::2].flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

## Copy the data

In [45]:
sampeCopyData=sampeData

In [46]:
sampeCopyData

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]], dtype=int32)

In [47]:
sampeData[1][3]=15

In [48]:
sampeData

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 15, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]], dtype=int32)

In [49]:
sampeCopyData

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 15, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]], dtype=int32)

the above operation just referred to the same location, to make a true copy we use .copy()

In [50]:
sampetrueCopy=sampeData.copy()

In [51]:
sampetrueCopy[1][3]=1000

In [52]:
sampetrueCopy

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12, 1000,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29]],
      dtype=int32)

In [53]:
sampeData

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 15, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]], dtype=int32)

## Mathematical Operations (Axis Wise Evaluations)

In [54]:
varA_1=list(range(0,2000))
varA_2=list(range(2000,4000))
varA_3=list(range(4000,6000))
varACom=[varA_1,varA_2,varA_3]

In [55]:
data=np.array(varACom)

In [56]:
data

array([[   0,    1,    2, ..., 1997, 1998, 1999],
       [2000, 2001, 2002, ..., 3997, 3998, 3999],
       [4000, 4001, 4002, ..., 5997, 5998, 5999]])

In [57]:
data.shape,data.size

((3, 2000), 6000)

In [58]:
np.sum(data)

17997000

In [59]:
np.sum(data,axis=0)

array([ 6000,  6003,  6006, ..., 11991, 11994, 11997])

In [60]:
np.sum(data,axis=1)

array([1999000, 5999000, 9999000])

## 1 for rows 0 for columns

In [61]:
np.max(data)

5999

In [62]:
np.max(data,axis=0)

array([4000, 4001, 4002, ..., 5997, 5998, 5999])

In [63]:
np.max(data,axis=1)

array([1999, 3999, 5999])

## Random numbers / Reshape

In [64]:
randSamData=np.random.random(6000)

In [65]:
randSamData

array([0.82572898, 0.53660424, 0.4040614 , ..., 0.97608721, 0.02833829,
       0.24790488])

In [66]:
randSamData.size

6000

In [67]:
randSamData.shape

(6000,)

In [68]:
matrixFromRandom=randSamData.reshape(200,30)

In [69]:
matrixFromRandom.shape

(200, 30)

In [70]:
matrixFromRandom.sum()

2983.80520554816

In [71]:
np.sum(matrixFromRandom)

2983.80520554816

In [72]:
np.sum(matrixFromRandom,axis=1).size

200

In [73]:
np.sum(matrixFromRandom,axis=0).size

30

In [74]:
matrixFromRandom.sum(axis=1).shape

(200,)

## Example 1

create a numpy array with random numbers and get the numbers closest to .50 

In [75]:
sampData=np.random.random(25)

In [76]:
sampData=sampData.reshape(5,5)

In [77]:
sampData=abs(sampData-.5)

In [78]:
np.argmin(sampData,axis=0)

array([2, 0, 3, 3, 4])

In [79]:
sampData

array([[0.39823509, 0.00560765, 0.17527356, 0.20473762, 0.03430552],
       [0.15170688, 0.04398605, 0.16322243, 0.26525802, 0.36079733],
       [0.02405334, 0.01966013, 0.4577941 , 0.1825316 , 0.09880768],
       [0.27417647, 0.09269578, 0.06259093, 0.18222322, 0.47722139],
       [0.04752044, 0.45463553, 0.10366636, 0.19500759, 0.00986937]])

In [80]:
np.argmin(sampData,axis=1)

array([1, 1, 1, 2, 4])

In [81]:
#np.argmin(abs(matrixFromRandom-.50),axis=1)

In [82]:
#np.argmin(abs(matrixFromRandom[0]-.50))

In [83]:
matrixFromRandom[0]

array([0.82572898, 0.53660424, 0.4040614 , 0.59174816, 0.60899906,
       0.30276393, 0.4338271 , 0.18639595, 0.06933189, 0.69292074,
       0.46412117, 0.26034365, 0.36384388, 0.49077924, 0.77932979,
       0.56482016, 0.70517588, 0.34155363, 0.30494889, 0.07312372,
       0.18859826, 0.21531343, 0.29030035, 0.00485094, 0.06698516,
       0.20324938, 0.56114453, 0.18206705, 0.41602418, 0.10526804])

## Example 2

##### select the top 5 columns on order of highest variance

In [84]:
sampData2=np.random.random(6000)

In [85]:
sampData2=sampData2.reshape(100,60)

In [86]:
varInfo=np.var(sampData2,axis=0)

In [87]:
varInfo

array([0.08855563, 0.07867347, 0.09135612, 0.09125   , 0.0816446 ,
       0.09270102, 0.08452573, 0.07322098, 0.07930801, 0.07469763,
       0.06972668, 0.08401985, 0.07011578, 0.07596773, 0.08778371,
       0.09111618, 0.07440067, 0.07408599, 0.09477131, 0.08821468,
       0.08112578, 0.0726896 , 0.08814488, 0.08131774, 0.07936664,
       0.08136125, 0.08656931, 0.07846416, 0.0819849 , 0.06577238,
       0.08306621, 0.08625741, 0.07079062, 0.08580291, 0.07993636,
       0.0924897 , 0.08943308, 0.08995811, 0.08206755, 0.0832003 ,
       0.09380986, 0.08809525, 0.08223657, 0.08702499, 0.08346123,
       0.08314001, 0.08754624, 0.08411141, 0.09101148, 0.08549934,
       0.08410199, 0.09431237, 0.0876723 , 0.07091267, 0.08442426,
       0.08986065, 0.08775663, 0.09117069, 0.08161488, 0.09065804])

In [88]:
incOrder=np.argsort(varInfo)

In [89]:
incOrder[-5:]

array([35,  5, 40, 51, 18])

In [90]:
sampData2[:,incOrder[-5:]]

array([[0.94756539, 0.9171215 , 0.62118558, 0.40498072, 0.49955732],
       [0.63444729, 0.00322051, 0.98922906, 0.99176488, 0.95174702],
       [0.91244781, 0.7921247 , 0.04191832, 0.03413293, 0.79888859],
       [0.02995028, 0.98096122, 0.01086874, 0.50886999, 0.23214908],
       [0.4300224 , 0.32957921, 0.81877168, 0.85242317, 0.75473377],
       [0.89747057, 0.67906147, 0.51455513, 0.25372238, 0.46211523],
       [0.91244929, 0.75904893, 0.76096479, 0.49621734, 0.90737192],
       [0.297296  , 0.3121376 , 0.55136698, 0.91794095, 0.77612411],
       [0.39987985, 0.25886438, 0.49104999, 0.73546774, 0.94855793],
       [0.8596767 , 0.41188923, 0.79223248, 0.08446089, 0.96698508],
       [0.69693628, 0.2771864 , 0.76930164, 0.13455697, 0.25612551],
       [0.90738793, 0.68777174, 0.99551089, 0.5283829 , 0.76978589],
       [0.67890836, 0.72880613, 0.73058585, 0.25178726, 0.11168895],
       [0.99027847, 0.0770703 , 0.51739493, 0.56413565, 0.65628022],
       [0.20528775, 0.56064745, 0.

In [91]:
sampData


array([[0.39823509, 0.00560765, 0.17527356, 0.20473762, 0.03430552],
       [0.15170688, 0.04398605, 0.16322243, 0.26525802, 0.36079733],
       [0.02405334, 0.01966013, 0.4577941 , 0.1825316 , 0.09880768],
       [0.27417647, 0.09269578, 0.06259093, 0.18222322, 0.47722139],
       [0.04752044, 0.45463553, 0.10366636, 0.19500759, 0.00986937]])

In [92]:
np.var(sampData,axis=0)

array([0.01983255, 0.02832065, 0.01926053, 0.00095001, 0.0352959 ])

In [93]:
orderOfCol=np.argsort(np.var(sampData,axis=0))

In [94]:
orderOfCol[-5:]

array([3, 2, 0, 1, 4])

In [95]:
sampData.shape

(5, 5)

In [96]:
sampData[:,orderOfCol[-5:]].shape

(5, 5)

## Broadcasting

In [97]:
sampData4=np.random.random(28).reshape(7,4)

In [98]:
sampData4

array([[0.89095438, 0.06044462, 0.23535078, 0.19284026],
       [0.82815557, 0.85014023, 0.01167574, 0.22221126],
       [0.50009866, 0.54303388, 0.37963508, 0.71894607],
       [0.49083994, 0.03731297, 0.21782154, 0.70254232],
       [0.33977684, 0.06997354, 0.64124542, 0.88090304],
       [0.41876056, 0.32559608, 0.59865951, 0.12984081],
       [0.36552007, 0.40325888, 0.08155984, 0.98448812]])

In [99]:
sampData4+5

array([[5.89095438, 5.06044462, 5.23535078, 5.19284026],
       [5.82815557, 5.85014023, 5.01167574, 5.22221126],
       [5.50009866, 5.54303388, 5.37963508, 5.71894607],
       [5.49083994, 5.03731297, 5.21782154, 5.70254232],
       [5.33977684, 5.06997354, 5.64124542, 5.88090304],
       [5.41876056, 5.32559608, 5.59865951, 5.12984081],
       [5.36552007, 5.40325888, 5.08155984, 5.98448812]])

In [100]:
sampData4+np.array([1,2,3,4])

array([[1.89095438, 2.06044462, 3.23535078, 4.19284026],
       [1.82815557, 2.85014023, 3.01167574, 4.22221126],
       [1.50009866, 2.54303388, 3.37963508, 4.71894607],
       [1.49083994, 2.03731297, 3.21782154, 4.70254232],
       [1.33977684, 2.06997354, 3.64124542, 4.88090304],
       [1.41876056, 2.32559608, 3.59865951, 4.12984081],
       [1.36552007, 2.40325888, 3.08155984, 4.98448812]])

In [101]:
# it will give an error
# sampData4+np.array([1,2,3])

ValueError: ignored

In [ ]:
sampData4+np.array([1,2,3,4,5,6,7])

In [ ]:
sampData4+np.array([1,2,3,4,5,6,7]).reshape(7,1)

In [ ]:
np.array([1,2,3,4,5,6,7]).reshape(7,1)

In [ ]:
np.array([[1],[2],[3],[4],[5],[6],[7]]).shape

In [ ]:
sampData4+np.array([[1],[2],[3],[4],[5],[6],[7]])

##  Many matrix languages

In [102]:
aMatrix = np.array( [[1,1],[0,1]] )
bMatrix = np.array( [[2,0],[3,4]] )

In [103]:
aMatrix

array([[1, 1],
       [0, 1]])

In [104]:
bMatrix

array([[2, 0],
       [3, 4]])

In [105]:
aMatrix * bMatrix  #elementwise  multiplication

array([[2, 0],
       [0, 4]])

In [106]:
aMatrix.dot(bMatrix) # matrix product

array([[5, 4],
       [3, 4]])

In [107]:
np.dot(aMatrix,bMatrix)

array([[5, 4],
       [3, 4]])

In [108]:
aMatrix @ bMatrix  # matrix product

array([[5, 4],
       [3, 4]])

## Handy functions

In [109]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [110]:
type(np.ones((5,5)))

numpy.ndarray

In [111]:
arrayOf1s=np.ones((5,5))

In [112]:
arrayOf1s.dtype

dtype('float64')

In [113]:
np.ones((5,5),dtype='int32')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [114]:
exqualSpacedArray = np.linspace(0,10,30)

In [115]:
exqualSpacedArray

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [116]:
np.exp(exqualSpacedArray)  #e^x

array([1.00000000e+00, 1.41174649e+00, 1.99302816e+00, 2.81365052e+00,
       3.97216126e+00, 5.60768473e+00, 7.91662926e+00, 1.11762736e+01,
       1.57780651e+01, 2.22746281e+01, 3.14461281e+01, 4.43939611e+01,
       6.26730189e+01, 8.84784147e+01, 1.24909092e+02, 1.76339972e+02,
       2.48947338e+02, 3.51450531e+02, 4.96159055e+02, 7.00450807e+02,
       9.88858971e+02, 1.39601819e+03, 1.97082378e+03, 2.78230356e+03,
       3.92790730e+03, 5.54520936e+03, 7.82842987e+03, 1.10517584e+04,
       1.56022812e+04, 2.20264658e+04])

## np.arange

In [117]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [118]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Other useful functions

In [119]:
simpleArray=np.arange(0,16,2)

In [120]:
np.exp(simpleArray)

array([1.00000000e+00, 7.38905610e+00, 5.45981500e+01, 4.03428793e+02,
       2.98095799e+03, 2.20264658e+04, 1.62754791e+05, 1.20260428e+06])

In [121]:
np.sum(simpleArray)

56

In [122]:
np.sqrt(simpleArray)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739])

In [123]:
simpleArraySq=np.sqrt(simpleArray)

In [124]:
simpleArraySq

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739])

In [125]:
np.add(simpleArray,simpleArraySq)

array([ 0.        ,  3.41421356,  6.        ,  8.44948974, 10.82842712,
       13.16227766, 15.46410162, 17.74165739])

## What if some non supported operations

In [126]:
import numpy as np

In [127]:
np.fromfunction(  )

TypeError: ignored

In [128]:
def funcArray(x,y):
    return 3*x+2*y

functionCreatedArray = np.fromfunction(funcArray,(15,4),dtype=int)
functionCreatedArray

array([[ 0,  2,  4,  6],
       [ 3,  5,  7,  9],
       [ 6,  8, 10, 12],
       [ 9, 11, 13, 15],
       [12, 14, 16, 18],
       [15, 17, 19, 21],
       [18, 20, 22, 24],
       [21, 23, 25, 27],
       [24, 26, 28, 30],
       [27, 29, 31, 33],
       [30, 32, 34, 36],
       [33, 35, 37, 39],
       [36, 38, 40, 42],
       [39, 41, 43, 45],
       [42, 44, 46, 48]])

### Flat the array

In [129]:
functionCreatedArray.ravel()

array([ 0,  2,  4,  6,  3,  5,  7,  9,  6,  8, 10, 12,  9, 11, 13, 15, 12,
       14, 16, 18, 15, 17, 19, 21, 18, 20, 22, 24, 21, 23, 25, 27, 24, 26,
       28, 30, 27, 29, 31, 33, 30, 32, 34, 36, 33, 35, 37, 39, 36, 38, 40,
       42, 39, 41, 43, 45, 42, 44, 46, 48])

In [130]:
functionCreatedArray.shape

(15, 4)

In [131]:
reshapedArray=functionCreatedArray.reshape((15,4,1))

In [132]:
reshapedArray

array([[[ 0],
        [ 2],
        [ 4],
        [ 6]],

       [[ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[ 6],
        [ 8],
        [10],
        [12]],

       [[ 9],
        [11],
        [13],
        [15]],

       [[12],
        [14],
        [16],
        [18]],

       [[15],
        [17],
        [19],
        [21]],

       [[18],
        [20],
        [22],
        [24]],

       [[21],
        [23],
        [25],
        [27]],

       [[24],
        [26],
        [28],
        [30]],

       [[27],
        [29],
        [31],
        [33]],

       [[30],
        [32],
        [34],
        [36]],

       [[33],
        [35],
        [37],
        [39]],

       [[36],
        [38],
        [40],
        [42]],

       [[39],
        [41],
        [43],
        [45]],

       [[42],
        [44],
        [46],
        [48]]])

In [133]:
reshapedArray.shape

(15, 4, 1)

In [134]:
reshapedArray.ravel()

array([ 0,  2,  4,  6,  3,  5,  7,  9,  6,  8, 10, 12,  9, 11, 13, 15, 12,
       14, 16, 18, 15, 17, 19, 21, 18, 20, 22, 24, 21, 23, 25, 27, 24, 26,
       28, 30, 27, 29, 31, 33, 30, 32, 34, 36, 33, 35, 37, 39, 36, 38, 40,
       42, 39, 41, 43, 45, 42, 44, 46, 48])

## Reshape in new form

In [135]:
newArr=np.arange(640)

In [136]:
multiDimArr=newArr.reshape(40,4,4)

In [137]:
newArr.shape

(640,)

In [138]:
multiDimArr.shape

(40, 4, 4)

In [139]:
multiDimArr[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### make it as row vector by inserting an axis along first dimension

In [140]:
newArr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [141]:
newArr[np.newaxis,:]

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177

In [142]:
newArr[np.newaxis,:].shape

(1, 640)

In [143]:
newArr[:,np.newaxis]

array([[  0],
       [  1],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9],
       [ 10],
       [ 11],
       [ 12],
       [ 13],
       [ 14],
       [ 15],
       [ 16],
       [ 17],
       [ 18],
       [ 19],
       [ 20],
       [ 21],
       [ 22],
       [ 23],
       [ 24],
       [ 25],
       [ 26],
       [ 27],
       [ 28],
       [ 29],
       [ 30],
       [ 31],
       [ 32],
       [ 33],
       [ 34],
       [ 35],
       [ 36],
       [ 37],
       [ 38],
       [ 39],
       [ 40],
       [ 41],
       [ 42],
       [ 43],
       [ 44],
       [ 45],
       [ 46],
       [ 47],
       [ 48],
       [ 49],
       [ 50],
       [ 51],
       [ 52],
       [ 53],
       [ 54],
       [ 55],
       [ 56],
       [ 57],
       [ 58],
       [ 59],
       [ 60],
       [ 61],
       [ 62],
       [ 63],
       [ 64],
       [ 65],
       [ 66],
       [ 67],
       [ 68],
       [ 69],
       [ 70],
      

In [144]:
newArr[:,np.newaxis].shape

(640, 1)

In [145]:
newlist=np.arange(20)

Np.newaxis uses the slicing operator to recreate the array, while np.reshape reshapes the array to the desired layout (assuming that the dimensions match, this is must for a reshape to happen).

Np.newaxis just add another dimension where it has been specified, but reshape changes the entire data in valid computation and rearrangement.

## Numpy Where

In [146]:
cExampleData=np.arange(100,500,50)

In [147]:
cExampleData

array([100, 150, 200, 250, 300, 350, 400, 450])

In [148]:
np.where(cExampleData <300)

(array([0, 1, 2, 3]),)

In [149]:
cExampleData[np.where(cExampleData <300)]

array([100, 150, 200, 250])

## Dense layer calculation using numpy

In [ ]:
import numpy as np

In [155]:
inputLayer=np.random.random(20)

In [156]:
inputLayer

array([0.11063313, 0.31251765, 0.79811529, 0.94930949, 0.53243437,
       0.53467538, 0.86625889, 0.2920519 , 0.82674939, 0.29913445,
       0.14077846, 0.76907578, 0.02036023, 0.743692  , 0.90333526,
       0.88677811, 0.53595117, 0.64214603, 0.00119373, 0.56375592])

In [157]:
hiddenLayer=np.random.randn(500,20)

In [158]:
biasLayer=np.random.random(500)

In [159]:
inputLayer.shape, hiddenLayer.shape,biasLayer.shape

((20,), (500, 20), (500,))

In [163]:
outputL=np.dot(hiddenLayer,inputLayer)+biasLayer

In [161]:
outputL.shape

(500,)

In [ ]:
np.maximum(0,outputL)

array([0.00000000e+00, 4.09293249e+00, 0.00000000e+00, 0.00000000e+00,
       4.81268902e+00, 2.76360385e+00, 0.00000000e+00, 2.72644382e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.65591123e+00,
       0.00000000e+00, 2.00583890e+00, 0.00000000e+00, 0.00000000e+00,
       1.29607326e+00, 0.00000000e+00, 0.00000000e+00, 2.45720653e+00,
       4.40431500e+00, 0.00000000e+00, 2.80632553e+00, 0.00000000e+00,
       0.00000000e+00, 3.54960351e+00, 6.57224915e+00, 4.85467633e-03,
       0.00000000e+00, 2.57976916e+00, 7.03988148e+00, 3.01541599e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       6.50900448e-01, 0.00000000e+00, 1.15352058e+00, 2.74336706e+00,
       3.80829779e+00, 6.53158701e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 1.71125197e+00, 0.00000000e+00, 7.51761770e-01,
       0.00000000e+00, 2.32432261e+00, 3.66854252e+00, 3.81600965e-01,
       7.99193511e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
      

## Convolution layer using Numpy

In [165]:
15*15*3

675

In [166]:
imageData=np.random.rand(225).reshape(15,15)

In [167]:
imageData.shape

(15, 15)

In [168]:
imageData[0:3,1:4]

array([[0.52228651, 0.48377168, 0.32348478],
       [0.35643262, 0.52019921, 0.03022237],
       [0.57334889, 0.32301998, 0.5419057 ]])

In [169]:
imageData[:5,:5]

array([[0.21962223, 0.52228651, 0.48377168, 0.32348478, 0.80512529],
       [0.10904302, 0.35643262, 0.52019921, 0.03022237, 0.0319561 ],
       [0.22097577, 0.57334889, 0.32301998, 0.5419057 , 0.71017751],
       [0.05496197, 0.08986714, 0.42158467, 0.46832448, 0.16937432],
       [0.15108905, 0.17668317, 0.12162155, 0.96281115, 0.70438966]])

In [170]:
filterSize=np.array([[1,0,0],[0,1,0],[0,0,1]])

In [171]:
filterSize.shape

(3, 3)

In [ ]:
for k in range(13):
    for j in range(13):
        print (k,'row ',(k,k+3),(j,j+3))

0 row  (0, 3) (0, 3)
0 row  (0, 3) (1, 4)
0 row  (0, 3) (2, 5)
0 row  (0, 3) (3, 6)
0 row  (0, 3) (4, 7)
0 row  (0, 3) (5, 8)
0 row  (0, 3) (6, 9)
0 row  (0, 3) (7, 10)
0 row  (0, 3) (8, 11)
0 row  (0, 3) (9, 12)
0 row  (0, 3) (10, 13)
0 row  (0, 3) (11, 14)
0 row  (0, 3) (12, 15)
1 row  (1, 4) (0, 3)
1 row  (1, 4) (1, 4)
1 row  (1, 4) (2, 5)
1 row  (1, 4) (3, 6)
1 row  (1, 4) (4, 7)
1 row  (1, 4) (5, 8)
1 row  (1, 4) (6, 9)
1 row  (1, 4) (7, 10)
1 row  (1, 4) (8, 11)
1 row  (1, 4) (9, 12)
1 row  (1, 4) (10, 13)
1 row  (1, 4) (11, 14)
1 row  (1, 4) (12, 15)
2 row  (2, 5) (0, 3)
2 row  (2, 5) (1, 4)
2 row  (2, 5) (2, 5)
2 row  (2, 5) (3, 6)
2 row  (2, 5) (4, 7)
2 row  (2, 5) (5, 8)
2 row  (2, 5) (6, 9)
2 row  (2, 5) (7, 10)
2 row  (2, 5) (8, 11)
2 row  (2, 5) (9, 12)
2 row  (2, 5) (10, 13)
2 row  (2, 5) (11, 14)
2 row  (2, 5) (12, 15)
3 row  (3, 6) (0, 3)
3 row  (3, 6) (1, 4)
3 row  (3, 6) (2, 5)
3 row  (3, 6) (3, 6)
3 row  (3, 6) (4, 7)
3 row  (3, 6) (5, 8)
3 row  (3, 6) (6, 9)
3 row  

In [172]:
filSize=3
outputVal=[]
for k in range(13):
    for j in range(13):
        sampD=imageData[k:k+filSize,j:j+filSize]
        outputVal.append(np.sum(sampD*filterSize))
#         print (k,'row ',(k,k+3),(j,j+3))

In [ ]:
len(outputVal)

169

In [ ]:
outputFinal2=np.array(outputVal).reshape(13,13)

In [ ]:
outputFinal2

array([[1.0495371 , 1.62051323, 1.36326517, 0.91646237, 1.71875153,
        1.67074834, 2.71697971, 1.6912632 , 1.13366638, 2.04604664,
        1.43654909, 2.14876681, 1.878898  ],
       [1.57153447, 0.76550287, 1.07396812, 2.31744917, 1.15597923,
        1.51379036, 1.12099391, 2.5734717 , 1.24828424, 1.80346968,
        1.78734261, 1.01922192, 1.73783694],
       [1.64705099, 1.50713875, 0.38507759, 1.03620949, 1.67632773,
        1.13629366, 1.11367707, 1.02898951, 2.62844197, 1.74430282,
        1.94416258, 2.20916818, 1.07549053],
       [1.33505349, 1.67551555, 1.50177349, 0.37326999, 1.54713535,
        1.78851346, 1.01939233, 0.94988304, 1.60554458, 2.1981238 ,
        1.05950386, 2.21927968, 1.54866125],
       [1.34342432, 1.26388449, 1.68990795, 1.5040302 , 1.25616543,
        1.88934888, 1.4596106 , 1.4678751 , 1.85893118, 2.52640345,
        1.61745832, 1.02418836, 2.09583061],
       [0.96374296, 1.32861408, 1.22439521, 1.09616967, 1.35444114,
        1.32496959, 1.34372

In [173]:
sampD=imageData[:3,:3]

In [ ]:
# ((N-f)/s)+1

In [ ]:
(15-3)+1

13

## Function to try in numpy

 -  np.newaxis
 -  np.matrix
 -  np.tanh	Compute hyperbolic tangent element-wise.
 -  np.arcsinh	Inverse hyperbolic sine element-wise.
 -  np.arccosh	Inverse hyperbolic cosine, element-wise.
 -  np.arctanh	Inverse hyperbolic tangent element-wise.
 -  np.expm1	Calculate exp(x) – 1 for all elements in the array.
 -  np.exp2	Calculate 2**p for all p in the input array.
 -  np.log10	Return the base 10 logarithm of the input array, element-wise.
 -  np.log2	Base-2 logarithm of x.
 -  np.log1p	Return the natural logarithm of one plus the input array, element-wise.
 -  np.logaddexp	Logarithm of the sum of exponentiations of the inputs.
 -  np.logaddexp2	Logarithm of the sum of exponentiations of the inputs in base-2.
 -  np.add	Add arguments element-wise.
 -  np.positive	Numerical positive, element-wise.
 -  np.negative	Numerical negative, element-wise.
 -  np.multiply	Multiply arguments element-wise.
 -  np.power	First array elements raised to powers from second array, element-wise.
 -  np.subtract	Subtract arguments, element-wise.
 -  np.true_divide	Returns a true division of the inputs, element-wise.
 -  np.floor_divide	Return the largest integer smaller or equal to the division of the inputs.
 -  np.float_power	First array elements raised to powers from second array, element-wise.
 -  np.mod	Return the element-wise remainder of division.
 -  np.remainder	Return element-wise remainder of division.
 -  np.divmod	Return element-wise quotient and remainder simultaneously.

source:
 - https://www.youtube.com/watch?v=poD8ud4MxOY
 -      :https://numpy.org/
 -    :https://numpy.org/devdocs/user/quickstart.html